name: Generate ASCII Artwork

on:
    push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              run: sudo apt-get install cowsay -y

            - name: execute cowsay command
              run: cowsay -f dragon "Run for cover, Iam a DRAGON....RAWR" >> dragon.txt

            - name: test file exists
              run: grep -i "dragon" dragon.txt

            - name: read file
              run: cat dragon.txt

            - name: checkout repo files
              run: ls