name: exploring variables and secrets
env:
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME: mujahidhussain
    IMAGE_NAME: github-actions-nginx

on:
    push

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: docker build
              run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

            - name: docker login
              env:
                DOCKER_PASSWORD: s3cUrePassw0rd
              run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

            - name: docker publish
              run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

    deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps:
            - name: docker run
              run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest