name: exploring variables and secrets


on:
    workflow_dispatch: 
#    push

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: docker build
              run: echo docker build -t ${{vars.CONTAINER_REGISTRY}}/${{vars.DOCKER_USERNAME}}/${{vars.IMAGE_NAME}}:latest

            - name: docker login
              run: echo docker login --username=${{vars.DOCKER_USERNAME}} --password=${{secrets.DOCKER_SECRET}}

            - name: docker publish
              run: echo docker push ${{vars.CONTAINER_REGISTRY}}/${{vars.DOCKER_USERNAME}}/${{vars.IMAGE_NAME}}:latest

    deploy:
        needs: docker
        runs-on: ubuntu-latest
        concurrency: 
            group: production-deployment
            cancel-in-progress: false
        steps:
            - name: docker run
              run: |
                echo docker run -d -p 8080:80 ${{vars.CONTAINER_REGISTRY}}/${{vars.DOCKER_USERNAME}}/${{vars.IMAGE_NAME}}:latest
                sleep 600